"""Public build-time settings for the browser game"""

SUPABASE_FUNCTION_URL = "__SUPABASE_FUNCTION_URL__"
DATA_CONTROLLER_NAME = "__DATA_CONTROLLER_NAME__"
DATA_CONTROLLER_EMAIL = "__DATA_CONTROLLER_EMAIL__"
DATA_RETENTION_PERIOD = "__DATA_RETENTION_PERIOD__"
PRIVACY_NOTICE_VERSION = "2026-08-05"
